[package]
name = "ldjam-55"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"

[profile.dev]
debug = 1
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
